### PR TITLE
feat: Visual Assistet Nozzle Offset Calibration for IDEX printers or Toolchangers

### PR DESCRIPTION
**Pull request by HelgeKeck**
## Description

All needed informations can be found here:
https://github.com/HelgeKeck/vcore-idex/blob/main/doc/vaoc.md

Atm this PR adds a overlay over a Adaptive MJPEG Streamer camera. 

This is not a good solution, i request help for a proper implementation.

Ideally this would be a completely own panel where i can choose any type camera.

### CODE REVIEW

**Comment by TypQxQ** [comment]
With multiple tools the coordinates are overlayed:
image

**Comment by HelgeKeck** [comment]
> With multiple tools the coordinates are overlayed: image

do you have 49 Toolheads?

**Comment by HelgeKeck** [comment]
but yes, this can be improved

**Comment by HelgeKeck** [comment]
so, i made some changes. everything works now as expected, settings page implementation is better, everything is translated, ...

next step would be a way to make this available for the other webcam panels as well, would appreciate some help

**Comment by HelgeKeck** [comment]
> > With multiple tools the coordinates are overlayed
image

**Comment by meteyou** [comment]
Thanks for all your work! I will check this PR as soon as possible and fix the package.lock issue.

**Comment by HelgeKeck** [comment]
> Thanks for all your work! I will check this PR as soon as possible and fix the package.lock issue.

no hurry, packagelock issue is foxed already. whenever oyu have time

**Comment by HelgeKeck** [comment]
even if i was able to add a universal overlay to each camera type, i realized it doesnt make a lot of sense now. the rendering strategies are to different for the camera types, this would require to much changes. 

i limited the webcam setting, to enable the overlay, to adaptivemjpeg cameras. i think thtats totally fine, you wont connect a IP or webrtc camera anyway as a nozzle cam

so from my point i am happy wiht it as it is now

**Comment by meteyou** [comment]
webrtc is just fine for nozzle cams, because you can also use higher resolutions and more FPS, but please let me check a "generic" option to implement it...

**Pull request closed without merging**
