### PR TITLE
fix: add theming for find/search panel

### PR DESCRIPTION
**Pull request by vajonam**
adding theme for search panel

### CODE REVIEW

**Comment by vajonam** [comment]
image

The main text is set to primary colour and re-using other background variables.

**Comment by vajonam** [comment]
updated LnF 
image

**Comment by vajonam** [comment]
@steadyjaw  anything more you need from me on this?

**Comment by steadyjaw** [comment]
awesome. thanks for your work.
looks cool. But I am still missing some styling.
image

Would be awesome, if you could dig a little bit deeper.

The following is not matching the Mainsail UI from my point of view
**General**
- needs a little bit more spacing (padding and margin on elements)

**Panel**
- background color -> maybe try "--v-panel-base" or "-v-toolbar-base"?

**Buttons**
- font weight too low
- more letter spacing 
- hover-effect -> no transition, wrong color
- if same as the panel color maybe they could be elevated or make them flat, we use both styles within the UI
Example:
image

**Close Button*
looks cool, I would have tried to add the mdi-close icon. But the way you did it, it looks ok
- no hover effect on the button, could you try to make it look like the other buttons with an icon only?

**text-areas**
looks totally different the the other
Example:
text-area

**Checkboxes**
same as above
Example:
checkboxes

Please let me know if you need something.
If some of the styling is too complex and it cannot be added to the codemirror config file, it is totally fine to add the styling to the "TheEditor" component in: https://github.com/mainsail-crew/mainsail/blob/develop/src/components/TheEditor.vue
There is a "styling" tag at the top. It says "scoped" and is empty. Maybe you have to remove the "scoped" prop.

**Comment by steadyjaw** [comment]
@vajonam 
you interested in doing some additional changes for this PR?

**Comment by vajonam** [comment]
> 

Sure, let me know what you more you want done?

**Comment by vajonam** [comment]
@steadyjaw  what else do you need me to do here?

**Comment by vajonam** [comment]
@th33xitus can you review this too :-) this is been sitting around forever

**Comment by th33xitus** [comment]
@vajonam can you update this PR and resolve all conflicts please? we can then have a look at it. also lets see what @meteyou has to add to this maybe.

**Comment by vajonam** [comment]
Sure. Will do this later today.

**Comment by vajonam** [comment]
will send new PR for this.

**Pull request closed without merging**
