### PR TITLE
feat: Improved toolhead selector buttons

### PR DESCRIPTION
**Pull request by HelgeKeck**
## Description

Improved toolhead selector buttons

Signed-off-by: Helge Keck <helgekeck@hotmail.com>

## Related Tickets & Documents

fixes: #1272 

## Mobile & Desktop Screenshots/Recordings
https://discord.com/channels/758059413700345988/901024829875027998/1154081960176648242
## [optional] Are there any post-deployment tasks we need to perform?

### CODE REVIEW

**Comment by HelgeKeck** [comment]
having problems to wrap the t buttons into multiple lines

**Comment by meteyou** [comment]
thx! i will check this PR asap. i think we have to convert the array of tools in a 2 dimension array. Dimension 1 -> row, dimension 2 -> tools.

**Comment by HelgeKeck** [comment]
image

**Comment by HelgeKeck** [comment]
image
image

**Comment by meteyou** [comment]
looks really nice! I don't know if it is needed to change the name/title...

I hope one of the crew has time to review my PR, then we have to update this PR from develop to move this code in the separate SFC.

**Comment by HelgeKeck** [comment]
image

**Comment by meteyou** [comment]
i think the "active" background color is enough. furthermore, the wrap does not work any more with custom titles, because you do not know what the customer writes in. "printing" is much longer than Tx.

**Comment by meteyou** [comment]
refactoring PR is merged. pls update your branch from develop: https://github.com/mainsail-crew/mainsail/pull/1565

**Comment by HelgeKeck** [comment]
i am sure there is a better vue way to do that. but it works so far

**Pull request closed without merging**
