### PR TITLE
locale(it): Italian translation of the Spoolman module

### PR DESCRIPTION
**Pull request by Giadej**

### CODE REVIEW

**Comment by meteyou** [comment]
@Giadej hey! thanks for your PR! Do you have also time to translate all other missing keys in the italian translation file?

**Comment by Giadej** [comment]
> @Giadej hey! thanks for your PR! Do you have also time to translate all other missing keys in the italian translation file?

No, I don't but I can see

**Review by meteyou — APPROVED** [review]

**Comment by meteyou** [comment]
@Giadej i merged this PR and if you have time, feel free to create another PR with the rest of the italian translations. Thx!

**Comment by Giadej** [comment]
> @Giadej i merged this PR and if you have time, feel free to create another PR with the rest of the italian translations. Thx!

Sure, I'm already at work!

**Pull request merged**
