### PR TITLE
locale(es): Typos/grammar review

### PR DESCRIPTION
**Pull request by drChelo**
Full review of the ES language.

### CODE REVIEW

**Review by th33xitus — CHANGES_REQUESTED** [review]
Hi, thank you for your contribution.
Sadly there went something wrong with all indentations. I assume your Editor/IDE you use replaced all indentations with spaces with indentations with tabs. We can't merge that this way.

Please make sure your Editor/IDE follows our file formatting.

**Comment by drChelo** [comment]
Hi!

I changed the file by replacing the indentations with spaces, as per the original file.
I don't know if I have to make the Pull request again (I uploaded the modified file to my fork).

Cheers,
-M

**Comment by th33xitus** [comment]
> Hi!
> 
> I changed the file by replacing the indentations with spaces, as per the original file. I don't know if I have to make the Pull request again (I uploaded the modified file to my fork).
> 
> Cheers, -M

Okay that worked. But now i saw that there is still an issue. You seem to use CRLF as linefeeds. We need LF linefeeds.
If you have a look at the file here: https://github.com/mainsail-crew/mainsail/pull/689/files you can see that your PR replaces the full content of the file. I didn't saw the possibly wrong linefeeds before you had the indents fixed. But now it points to wrong linefeeds.

**Comment by drChelo** [comment]
Ok! Third thime's the charm! lol

I opened the file with VSC and changed to LF, it would be useful now?

**Comment by drChelo** [comment]
Ok, third time's the charm! (maybe, haha)

I used VSC to change to LF, but I'm not sure I've done things correctly, cause now I see that I Merged the branch, maybe?

**Comment by th33xitus** [comment]
I think it is okay now. It's hard to tell because a lot of blocks seem to have changed their position inside of that file.

**Review by th33xitus — APPROVED** [review]

**Pull request merged**
