### PR TITLE
WIP: Docker cleanup

### PR DESCRIPTION
**Pull request by mamoit**
Hello,

I stumbled on this project and saw that you could use a little help with your docker images.

I did some refactoring focusing on 3 points: readability, layer count and image size.

The `node` image went from:
- 927MB to 909MB
- 14 layers to 12

The `api` image went from:
- 2.63GB to 1.91GB
- 29 layers to 14 layers

If `buster-slim` is used the `node` image can be shrunk further to 178MB.

The `api` image had a more "violent" refactor, and the `no-install-recommends` on apt is the best candidate to break something, but it shaves 700MB off the image.

I don't really know how to test if these changes break someone's workflow, so if someone could help me out to make sure it would be great.
Let me know if you'd like to see something changed or if you had something in mind that I may include in this refactor.

### CODE REVIEW

**Comment by meteyou** [comment]
thx for your work! docker will be used for developing. you can find the guide here: https://docs.mainsail.xyz/development/docker

@freasy is our docker guy. if you have questions, feel free to ping him.

**Comment by freasy** [comment]
@mamoit i am @un!t#6860 on discord :)

**Comment by speendo** [comment]
I would find this very useful. May I ask why this was closed, @th33xitus?

**Comment by th33xitus** [comment]
@speendo This PR is all about the changes proposed by mamoit and not the idea proposed by @mkuf.
He is free to create his own PR or open a feature request for us to further evaluate on his idea.

This PR (the proposed changes you can see in the files tab - that's what it's all about) isn't usefull to us anymore in its current form. Most of the files don't even exist in the current develop branch anymore and even the Docker project for developing has seen a huge rework and basically got newly written from the ground up.

**Comment by pataar** [comment]
> I would find this very useful. May I ask why this was closed, @th33xitus?

If you'd like to simulate a printer you can use: https://github.com/mainsail-crew/virtual-klipper-printer

That image already has these improvements built-in.

**Comment by speendo** [comment]
Thanks @th33xitus and @pataar.

In fact, I don't want to simulate a printer. I want to run the whole stack (klipper, moonraker, Mainsail) on my home server using docker. Actually, I do that already using https://github.com/mkuf/prind.

However, I would have more confidence in terms of things-won't-break if the Mainsail docker image would come from this project and not from a third party project (no offense @mkuf, you do a great job).

**Comment by pataar** [comment]
> Thanks @th33xitus and @pataar.
> 
> In fact, I don't want to simulate a printer. I want to run the whole stack (klipper, moonraker, Mainsail) on my home server using docker. Actually, I do that already using https://github.com/mkuf/prind.
> 
> However, I would have more confidence in terms of things-won't-break if the Mainsail docker image would come from this project and not from a third party project (no offense @mkuf, you do a great job).

We currently have a Docker image in the works. Currently only the 'edge' tag is available. Which is the latest version of Mainsail but might be unstable: https://github.com/mainsail-crew/mainsail/pkgs/container/mainsail

**Comment by pataar** [comment]
@speendo We've added the `:latest` tag to our docker image. This is running version 2.1.2. You can use:

```sh
docker pull ghcr.io/mainsail-crew/mainsail:latest
```

https://github.com/mainsail-crew/mainsail/pkgs/container/mainsail

**Comment by speendo** [comment]
thank you

**Pull request closed without merging**
