### PR TITLE
feat: add bed aspect ratio to heightmap graph

### PR DESCRIPTION
**Pull request by EmJay276**
## Description

This PR adds  the bed aspect ratio to the heightmap graph.
This is espacially usefull for highly non square print beads (mine is 600 x 300), see Screenshots below.

## Related Tickets & Documents

None

### Mobile
<td valign="center"> </td>
<td valign="center"> </td>

## [optional] Are there any post-deployment tasks we need to perform?

No

Signed-off-by: Michael Jäger michael@mjaeger.eu

### CODE REVIEW

**Comment by meteyou** [comment]
Thx for your PR!

**Comment by EmJay276** [comment]
Thanks for reviewing it that fast 👍

If min(XYRange) is 0 (this can only be the case if one direction has only 1 be neat point), isn't there a problem with a 0 wide/depth graph? Even if we are not dividing by 0?

0/1 = 0

I will check later and open a PR if needed.

**Comment by meteyou** [comment]
Thx for your hint! I had not thought about this case at all. It is very unusual, but we should merge a fix if it could happen.

**Comment by EmJay276** [comment]
I tried to create a bed mesh with a X/Y distance of 0, but klipper won't allow this kind of settings (see below).
I think we don't need to check this case, if the bed with id 0, we have other problems than a heightmap graph not showing up.

Only 1 point along an axis is invalid: `Option 'probe_count' in section bed_mesh must have a minimum of 3`
Setting min/max points to the same value is also invalid: `bed_mesh: invalid min/max points`

I also noticed, having the mesh on a part of the bed, the graph will still ajust to the size of the bed (which was it doing the same way before but without axis scaling).
Which is perfectly fine I think.

Mesh with 290 x 290, bed 300 x 600

**Pull request merged**
