### PR TITLE
fix: added features for disabled state, busy state.

### PR DESCRIPTION
**Pull request by vajonam**
added features to get on par with other control schemes.

- loading indicator for the axis being homed, disabled stepping during that
- disabled with proper colors while printing
- flashing indicator for loading. open to ideas on how to change this to spinner. 

https://user-images.githubusercontent.com/152501/208986203-8926b338-6032-4526-81a4-58cbb7a8f5c3.mp4

### CODE REVIEW

**Comment by meteyou** [comment]
Please clean up your CSS code. it's not useful to add every id to the selectors.

**Comment by vajonam** [comment]
I will see if can simplify this.

**Comment by meteyou** [comment]
@vajonam any news here?

**Comment by vajonam** [comment]
@meteyou I can re-base and try to clean it up some, but sill will need help with simplifying CSS. I wasn't sure there was much interest in this feature, so really didn't keep to upto date. I will work on this week with an update.

**Comment by vajonam** [comment]
I will re-open a new PR.

**Comment by meteyou** [comment]
If you need help, feel free to ping me. Even if this feature is not a must-have, I see no problem merging it if the code fits.

**Comment by vajonam** [comment]
Sorry I wont be submitting this PR. I have moved on from mainsail.

**Pull request closed without merging**
