### PR TITLE
feat: Reminders panel on the History page

### LINKED ISSUE #1129: Incremental reminders based on number of hours printed - i.e. lubricate, change filter media etc.
### Requested feature:

Since mainsail tracks total hours printed it would be very nice and useful to have customizable incremental reminders based on number of hours printed. 

For instance, a reminder to change filter media every 50 hours of printing. Or a reminder to lubricate rails every 500 hours ect.  

### Solves the following problem:

the need to track these things which we all should do, but probably no one does... especially the filter media. 

### Additional information:

I think this would be very useful and everyone could benefit from it.

### PR DESCRIPTION
**Pull request by jeremiahvpratt**
### This PR adds a Reminders panel, which allows users to create and manage incremental reminders based on an elapsed number of print hours since reminder creation.
This PR will fix #1129 

### How to use it:

1. Ensure history is enabled in your moonraker conf
2. In the History tab, click the "+" button in the Reminders panel
3. Add a name and print hours duration to your reminder
4. Print for that many hours, then observe a reminder appearing in notifications.
5. Repeat a reminder by right clicking it and selecting "repeat" - this resets the start time for the reminder to the current number of total print hours on the machine.
6. Delete a reminder by right clicking it and selecting "delete", or selecting multiple reminders with their checkboxes and clicking the red trash icon at the top of the Reminders panel.
7. Edit a reminder by right clicking it and selecting "edit".

### What's missing:
Translations, I'm not sure what the process is for adding them.

### Images:
**Reminders Panel**
Panel
**Create Dialog**
create
**Notification**
notification

Signed off by: Jeremiah Pratt <jeremiah.v.pratt@gmail.com>

### CODE REVIEW

**Comment by meteyou** [comment]
Thanks for your PR. I will look a little deeper during the next week.

What I already noticed in the description. I would directly set the reminder to "recurring" or "one-time" when creating it. Furthermore, I would add a "snooze" button to the reminder in the notifications and create a new entry when it is done so that you have a history of how and when you performed this action. For example, you can also see how often you changed the activated carbon in the nevermore and in which calendar cycle.

**Comment by jeremiahvpratt** [comment]
Thanks for the comment @meteyou , I will incorporate those changes over the coming week!

**Comment by jeremiahvpratt** [comment]
Hi @meteyou I've added a repeat button to the notifications, and the button is also accessible by right-clicking the reminder row on the history panel:
image
image

I've also added recording of two values when a reminder is repeated: a list of total print times at which the button was pressed, as well as a list of epoch timestamps. 

If it's alright with you, I think the feature might be better split into two PRs - this first one, which adds basic reminders functionality, and a follow-up PR that adds a detail view accessible by left-clicking a row on in the reminders panel. The plan would be for that detail view to show a table of past snoozes, with a date + time as well as a number of print hours since the last snooze.

**Comment by meteyou** [comment]
thx! i will test this code this week, comment if we have to "fix" something and then we can plan the next PR to extend this feature. thx for your work!

**Comment by jeremiahvpratt** [comment]
Hey @meteyou, is there any work for me to do on this PR?

**Comment by meteyou** [comment]
@jeremiahvpratt hey! yes i checked it already and i startet to refactoring some print history stuff for it. i will create a PR to your branch to discuss about it. i'm only a little bit busy atm...

**Comment by meteyou** [comment]
Sry for the long delay. I was the last two weeks not at home. I moved this feature to v2.7.0 and will post my branch soon.

**Comment by PhilBaz** [comment]
Any chance this feature will make it into the next release?

**Comment by meteyou** [comment]
@PhilBaz i dont think so. there are a lot of todos and i dont have the time right now...

**Comment by jeremiahvpratt** [comment]
Let me know if there’s anything that I could do to help!

*Jeremiah Pratt*
281-536-4530

**Comment by meteyou** [comment]
@jeremiahvpratt thx for your offer! at first i will make same background work

ok. i pushed my refactoring of the history list panel (and updated this branch). next step: i will combine these tables

**Review by dw-0 — APPROVED** [review]

**Pull request merged**
