### PR TITLE
locale(nl): update dutch localization

### PR DESCRIPTION
**Pull request by bartlammers**
Some empty strings still in there, but those were empty in the en.json as well so kept them as such.

### CODE REVIEW

**Comment by th33xitus** [comment]
I pushed a fix with replacing the tabs with spaces as we require them.
There are a lot of empty strings in that file. So a lot of missing translations.
In the current english locale file are only 2 emptry strings. I this one are around 44.

**Review by th33xitus — CHANGES_REQUESTED** [review]
I pushed a fix with replacing the tabs with spaces as we require them.
There are a lot of empty strings in that file. So a lot of missing translations.
In the current english locale file are only 2 emptry strings. I this one are around 44.

**Comment by bartlammers** [comment]
Updated the translations, removed the empty strings (was because of BabelEdit, they apparently still existed in other languages) and re-ran lint and prettier

**Comment by th33xitus** [comment]
Thank you, looks good to me now!

**Review by th33xitus — APPROVED** [review]

**Pull request merged**
