### PR TITLE
locale(se-SV): add swedish localization

### PR DESCRIPTION
**Pull request by eltacoloco**
Created Swedish translation

### CODE REVIEW

**Comment by eltacoloco** [comment]
I don't understand what I'm doing wrong, I tried using prettier to format everything. But the auto check is showing error for prettier when trying to pull

**Comment by th33xitus** [comment]
> But the auto check is showing error for prettier when trying to pull

It's probably because you used tabs for indentation this time. But that is no big issue. We can fix that.

**Comment by th33xitus** [comment]
I quickly fixed the file with running the linter on it and replace the tabs with whitespaces for indentation 😄

**Comment by eltacoloco** [comment]
> I quickly fixed the file with running the linter on it and replace the tabs with whitespaces for indentation 😄

Thank you, the file was starting to drive me insane.

**Review by th33xitus — APPROVED** [review]

**Comment by meteyou** [comment]
@eltacoloco hey! Are you also on our discord server? I want to invite you to the translator channel.

If yes, what is your username in discord?

**Comment by eltacoloco** [comment]
> @eltacoloco hey! Are you also on our discord server? I want to invite you to the translator channel.
> 
> If yes, what is your username in discord?

Hi, yes i'm on discord user:
ElTacoLoco#8473

**Pull request merged**
