### PR TITLE
FR: increase scale for those w/ warped beds

### PR DESCRIPTION
**Pull request by vajonam**
increase scale from 0.5 to 2 for those with warped beds who can never get it any better!

### CODE REVIEW

**Comment by vajonam** [comment]
also added saving, found that this wans't being saved

**Comment by meteyou** [comment]
this is only the "minimum" range. the min/max values automatically adjust to the mesh

**Comment by vajonam** [comment]
this for the box scale, to allow it to go past 0.5 to 2. this way 0.3 variance doesn't look as bad

**Comment by meteyou** [comment]
yes, because 0.3mm are really bad. thats why we use 0.5 as "min" box size to see anything.

**Comment by vajonam** [comment]
No worries. You can close the PR. I can keep this on my local build.

**Comment by vajonam** [comment]
@meteyou  what about the saving of the sate? that is possibly useful ? when a user selects the states to save it?

**Comment by meteyou** [comment]
@vajonam i dont know what you mean. can you explain it?

**Comment by vajonam** [comment]
The Scale slider position isn't' saved right now. every you you come back to page it gets reset. 

The PR include a bit to save that settings.

**Pull request closed without merging**
