### PR TITLE
locale(zh): update chinese locale

### PR DESCRIPTION
**Pull request by xiaoqianzi15**
update ...

### CODE REVIEW

**Comment by xiaoqianzi15** [comment]
update some zh translation. Simplified Chinese

**Comment by xiaoqianzi15** [comment]
updated

**Comment by meteyou** [comment]
i think you forget to commit or pushed your update.

**Comment by meteyou** [comment]
@xiaoqianzi15 sry for the ping again, but i cannot see a new commit with the last missing keys. can you push the commit please?

**Review by meteyou — APPROVED** [review]

**Pull request merged**
