### PR TITLE
feat: Tool changer buttons in extruder control panel

### PR DESCRIPTION
**Pull request by TypQxQ**
## Description

- Added a button for Tool Droppoff if there exists a macro named "TOOL_DROPOFF".
- Added a button for Tool Lock if there exists a macro named "TOOL_LOCK".
- Added a button for Tool Unlock if there exists a macro named "TOOL_UNLOCK".
- Swedish translation for Extruder Control Panel.

Not sure of the aesthetics as I have never before worked with Vue.

## Mobile & Desktop Screenshots/Recordings

image

### CODE REVIEW

**Comment by TypQxQ** [comment]
> Thx for your PR! Are these macro names a "standard"?

This are the commands I use in [KTCC ](https://github.com/TypQxQ/Klipper_ToolChanger) and that reflects the functionality. Same macros names are also used in [JubileeKlipper](https://github.com/Xonman/JubileeKlipper/tree/main/macros). I can't find other names used in Klipper for them.

`TOOL_DROPOFF`` is used by KTCC and in Xonman macros for Jubilee. I can't find any alternative names. The standard for it in RRF is ``T-1`` in Marlin it is ``G27``. T-1 is most logical but incompatible with Klipper naming. 

The ``TOOL_LOCK`` is named ``tool_lock`` in the RRF Jubilee reference while in e3d RRF it is named ``Coupler - Lock``.

**Comment by meteyou** [comment]
Are there any current efforts to merge this code into Klipper?

**Comment by TypQxQ** [comment]
> Are there any current efforts to merge this code into Klipper?
Not that I am aware.

I changed a little so the code looks for macros or commands now.
Also got the UI to look like I want:
image

**Comment by meteyou** [comment]
I don't think, that the word Tool- is necessary here. Is there also a state behind these buttons? So you can highlight the current state?

**Comment by TypQxQ** [comment]
> I don't think, that the word Tool- is necessary here. Is there also a state behind these buttons? So you can highlight the current state?

Something like this when known tool is selected vs. not selected:
image
image

This is based on existing toolchangeMacros.

Because the toollock can be locked with an unknown tool, manualy selected, mostly while testing, the unlock should allways be available.

**Comment by TypQxQ** [comment]
I do have a way to know if tool is unlocked for KTCC because when unlocked:
printer.ktcc.tool_current : -1

But that is only valid for KTCC.

**Comment by TypQxQ** [comment]
Something like this is posible:
image
image

**Comment by HelgeKeck** [comment]
you could make the lock/unlock buttons as one bistate button with a state icon in it

**Comment by TypQxQ** [comment]
> you could make the lock/unlock buttons as one bistate button with a state icon in it

It's really hard to see if that lock is open or closed. I believe it is much better having text buttons and always having the option to unlock, In essence that is how most locks initialize so it doubles as a reset, init of the lock.

As a sidenote I have the same pictogram in my electric car to lock or unlock the charger cable. It's a pain to see if it's locked or unlocked so by that experience I would not recommend it. Not without a better pictogram.

I still like this the best 😄
image

**Comment by TypQxQ** [comment]
> > > you could make the lock/unlock buttons as one bistate button with a state icon in it
> > 
> > 
> > It's really hard to see if that lock is open or closed. I believe it is much better having text buttons
> 
> colors

Has to follow the same design language as the rest of Mainsail. So colors would be bad idea but I found the alternative lock icon 😃 
image

**Comment by TypQxQ** [comment]
And like this with tooltips and a divider:
image
image

**Comment by meteyou** [comment]
> > Are there any current efforts to merge this code into Klipper?
> 
> Not that I am aware.

What is the reason for this? Usually, we only merge default klipper functions. Would it be possible to have a tool-changer printer with klipper without this "plugin"?

**Comment by TypQxQ** [comment]
> > > Are there any current efforts to merge this code into Klipper?
> > 
> > 
> > Not that I am aware.
> 
> What is the reason for this? Usually, we only merge default klipper functions. Would it be possible to have a tool-changer printer with klipper without this "plugin"?

This would work with any toolchanger using those commands. For example the klipper macros from Xon would work with this just as well as with the KTCC plugin.
This uses functionality from the current toolchangeMacros and adds possibility to use the "TOOL_DROPOFF", "TOOL_LOCK" and "TOOL_UNLOCK" macros or commands if available.

Had I been able to make plugins for Mainsail, I would but I am submitting pull requests as we discussed on Discord.

And I was planing to add more functionality specific to KTCC later.

**Comment by meteyou** [comment]
@TypQxQ but what is stopping you from merging this "plugin" into klipper now?

Do you know how to create Vue "plugins" for a precompiled app?

**Comment by TypQxQ** [comment]
@meteyou I have no idea 🤷 how to make a "plugin" for Vue.  Because it is all precompiled, I see that it lacks flexibility. This is regrettable. I was confused because I've never worked with precompiled web projects and although I see the benefits of it being faster on a small computer like the Pi, it's verry constrictive.
First I heard of it was when I looked into Mainsail project 😄. 
All my former web programming has been about extending the functionality 😃. First trough Perl in the '90s and later Java and .Net in the early '00s. I'm feeling old... 👴 

Reason of not merging the KTCC plugin to Klipper mainstream is because it changes some of the core functionality in Klipper. 

Klipper revolves around the Extruder. You can't not have an extruder active. In KTCC every tool can have or not have an extruder or partcooling fan. An extruder can be shared between multiple tools or no extruder being used at all. 

Temperature is in Klipper one temperature for every extruder while in KTCC one Tool has Active temperature, Standby temperature and HeaterState (Active, Standby and Off). Switching tools needs to switch Active to Standby on previous tool and to Active on Next Tool. Also, Standby temperature has configurable timeout. For example, if a tool is used only in the beginning of print it is prudent to have it shut down to off after 10 minutes in Standby than having it at Standby temperature for the rest of the print.

Partcooling fan is carried over when possible and it's possible to control the fan of an unused tool.

Log and Statistics like for HappyHare, per print and persisitent for tool unlocks, locks, and individual tool mounts, unmounts.

**Comment by meteyou** [comment]
> I have no idea 🤷 how to make a "plugin" for Vue. Because it is all precompiled, I see that it lacks flexibility. This is regrettable. I was confused because I've never worked with precompiled web projects and although I see the benefits of it being faster on a small computer like the Pi, it's verry constrictive.
> First I heard of it was when I looked into Mainsail project 😄.
> All my former web programming has been about extending the functionality 😃. First trough Perl in the '90s and later Java and .Net in the early '00s. I'm feeling old... 👴

It sounds like you have a lot more experience than me in web programming 😅. In my experience, Vue unfortunately doesn't offer any real possibility of modularly loading something that hasn't been compiled with the main app.

> Reason of not merging the KTCC plugin to Klipper mainstream is because it changes some of the core functionality in Klipper.
> Klipper revolves around the Extruder. You can't not have an extruder active. In KTCC every tool can have or not have an extruder or partcooling fan. An extruder can be shared between multiple tools or no extruder being used at all.
> Temperature is in Klipper one temperature for every extruder while in KTCC one Tool has Active temperature, Standby temperature and HeaterState (Active, Standby and Off). Switching tools needs to switch Active to Standby on previous tool and to Active on Next Tool. Also, Standby temperature has configurable timeout. For example, if a tool is used only in the beginning of print it is prudent to have it shut down to off after 10 minutes in Standby than having it at Standby temperature for the rest of the print.
> Partcooling fan is carried over when possible and it's possible to control the fan of an unused tool.

I have no influence on what will be merged in Klipper, but to me it all sounds like a good addition/further development of Klipper. Have you already had a conversation about this with Kevin?

**Comment by meteyou** [comment]
I am closing this PR because no response. Please create a new (up-to-date) PR if you want to continue working on this feature.

**Pull request closed without merging**
