### PR TITLE
locale(ja): update Japanese localization

### PR DESCRIPTION
**Pull request by chai-md**
follow-up en.json

### CODE REVIEW

**Review by meteyou — APPROVED** [review]

**Comment by meteyou** [comment]
Thanks for your PR! There are only one missing key and one unused key. Please add the missing key and delete the unused key.

Here is the result of the locale check:
image

**Comment by meteyou** [comment]
@chai-md any news to this PR? are you able to fix this minor issues?

**Comment by chai-md** [comment]
I was a little busy with another matter. Does this look good?

**Comment by meteyou** [comment]
> I was a little busy with another matter. Does this look good?

Thx! Looks perfect!

**Pull request merged**
