### PR TITLE
locale(da): update Danish localization

### PR DESCRIPTION
**Pull request by srbjessen**
Added missing translations

### CODE REVIEW

**Comment by srbjessen** [comment]
I have tried running prettier, but it keeps saying 1 error 🤷‍♂️

**Comment by th33xitus** [comment]
Please don't create new PRs and rather update the existing one. There are 2 keys still missing, can you add those as well?

**Comment by th33xitus** [comment]
There are still two keys missing:
* 'Files.ExtruderTemp'
* 'Panels.ZoffsetPanel.Clear'

**Comment by srbjessen** [comment]
Finally it should be correct...

**Comment by th33xitus** [comment]
Looks good! Thank you! We will merge it soon.

**Review by th33xitus — APPROVED** [review]

**Pull request merged**
