### PR TITLE
feat: extend system load panel

### PR DESCRIPTION
**Pull request by meteyou**
* add cpu usage
* add network interfaces

### CODE REVIEW

**Comment by meteyou** [comment]
preview of the new system panel:

image

**Comment by meteyou** [comment]
current state:

image

**Review by th33xitus — APPROVED** [review]

**Comment by gurusonwheels** [comment]
updated to mainsail v2.2.0-beta2 and my panel is dark and unreadable with firefox on windows pc. 
Screenshot 2022-05-15 at 15-03-06 Voron 2 2896

**Comment by th33xitus** [comment]
@gurusonwheels Instead of posting the same screenshot at several places in here, please respond to the issue you opened: https://github.com/mainsail-crew/mainsail/issues/807
Thank you.

**Pull request merged**
