### PR TITLE
feat: add devices dialog in editor

### PR DESCRIPTION
**Pull request by meteyou**
## Description

This PR adds a popup dialog for searching CAN, Serial, USB or Video devices in the editor.

## Related Tickets & Documents

PR in Moonraker to add this feature: https://github.com/Arksine/moonraker/pull/798

## Mobile & Desktop Screenshots/Recordings

localhost_8080_config (1)
localhost_8080_config (4)

## [optional] Are there any post-deployment tasks we need to perform?

- Publish the docs page for this feature.

### CODE REVIEW

**Review by dw-0 — APPROVED** [review]

**Comment by ccatlett1984** [comment]
Would it be possible to get a scroll bar in the UI, it is not intuitive if you have multiple MCUs that you have to scroll down to see them.

**Comment by meteyou** [comment]
@ccatlett1984 there is already a scrollbar in this dialog...

**Comment by ccatlett1984** [comment]
I'll have to try another theme, I'll attach screenshots.

**Comment by dw-0** [comment]
> I'll have to try another theme, I'll attach screenshots.

If you use a theme other than the Mainsail standard themes, you are more or less on your own, or on the creator of the theme. During development, we really can't take into account that custom themes don't break. Likewise, we cannot guarantee that features will always be displayed correctly with custom themes in addition to the Mainsail standard themes. That is simply impossible.

image

**Comment by ccatlett1984** [comment]
Completely understandable, I'll try switching themes.

**Pull request merged**
