### PR TITLE
locale(es): Update Spanish translation

### PR DESCRIPTION
**Pull request by lotusotho**
## Description
This PR updates/adds more lines to the Spanish translation

## Related Tickets & Documents
none

## Mobile & Desktop Screenshots/Recordings
none

## [optional] Are there any post-deployment tasks we need to perform?
none

### CODE REVIEW

**Comment by meteyou** [comment]
do you need help to find the "missing keys"?

**Comment by lotusotho** [comment]
No worries, I'll eventually translate them all, I'm learning about translation keys as I go haha

**Comment by lotusotho** [comment]
I'll make a PR whenever I have the full file

**Comment by meteyou** [comment]
@lotusotho thx! i'll leave this PR open for your commits. Except I publish a release before, then I merge this PR before the release.

**Comment by lotusotho** [comment]
Tried to fill as much missing keys as possible. There are 3 left, but I couldn't find them, nevertheless where is the lastest version of es.json

**Comment by meteyou** [comment]
Thx for your update. These are the last missing keys:

- Panels.KlippyStatePanel.PowerOn
- Settings.GeneralTab.MainsailSettingsMoonrakerDb
- Heightmap.CurrentMesh.Range

**Comment by lotusotho** [comment]
Nice! Thanks for the help!

**Review by meteyou — APPROVED** [review]

**Pull request merged**
