### PR TITLE
locale(ja): add Japanese translation

### PR DESCRIPTION
**Pull request by chai-md**
Created Japanese translation

### CODE REVIEW

**Comment by th33xitus** [comment]
Thank you for your contribution. Sadly i am not allowed to push onto this PR and quickly fix it myself to make it merge-ready.
So i ask you to fix the failed checks yourself. Please also run `lint:fix` on that file, as this will sort the keys according to our eslint rules.

**Comment by chai-md** [comment]
Thanks for letting me know, I formatted it with Prettier Extension on Visual Studio Code, but the error did not go away.
I tried overwriting ja.json with the contents of en.json to see how Prettier on github works, but the error did not change.

**Comment by th33xitus** [comment]
I see, im not quite sure if the issue is, that you committed the file with an indentation level of 2 spaces instead of 4. (we use 4 for locale json files)

Can you now, after you already created the PR allow pushes to your branch from maintainers like me? Then i would try again and run prettier on that file on my machine too and try to fix that somehow.

**Comment by chai-md** [comment]
Thank you kindly for your detailed explanation. It seems that my Prettier Extension was not reading the configuration file properly so I fixed the problem in my environment and reformatted it.

This seems to have solved the formatting problem. Thank you very much.

**Comment by th33xitus** [comment]
Okay now it looks good! We can merge that. Thanks again for your contribution.

**Review by th33xitus — APPROVED** [review]

**Pull request merged**
